name: diary_calendar_app
description: Calendar + Diary app (Step 3 - Diary CRUD with image)
publish_to: 'none'
version: 0.3.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  drift: ^2.18.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/
