name: diary_calendar_app
description: Calendar + Diary app (Step 5 - Settings & Stats)
publish_to: 'none'
version: 0.5.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  drift: ^2.18.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  image_picker: ^1.0.7

  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
